version: '3.9.9'

services:
  db:
    image: postgres:17
    container_name: courier-postgres
    environment:
      POSTGRES_DB: courierappDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerasdf
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: courier-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: courier-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/courierappDB
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: qwerasdf
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - db
      - redis

volumes:
  pgdata:
